# Generated by Django 4.1 on 2022-08-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
